name: Windows C++ Qt6 CMake Build

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"' -y
          choco install	qt6-base-dev -y

      #- name: Set Qt environment variables
        #run: |
          #$qtPath = (Get-ChildItem "C:\Qt\6.4.2\mingw_64" | Sort-Object LastWriteTime -Descending | Select-Object -First 1).FullName
          #echo "QTDIR=$qtPath" >> $GITHUB_ENV
          #echo "$qtPath\bin" >> $env:GITHUB_PATH

      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_PREFIX_PATH="C:\Qt\6.4.2\mingw_64\lib\cmake"

      - name: Build
        run: |
          cmake --build build --config Release
